name: POST New Book
trigger:
  type: http
  httpRequest:
    url: sample.dev.app
    route: /books
    method: POST
    contentType: application/json
    body: '{ "title": "foo", "author": "bar"}'
specs:
  - name: Assert that status code is 200
    selectors:  
      serviceName: goapp
      httpMethod: POST
      httpRoute: /books
      httpHost: sample.dev.app
    assertions:
      responseStatusCode: 200
      httpMethod: POST
      httpRoute: /books 
      httpHost: sample.dev.app
      serviceName: goapp
      name: gorm.Create
    maxRetries: 3
    retryInterval: 4
  